version: '3.8'

services:
  sweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sweb
    ports:
      - "5011:5011"
      - "5012:5012"
    volumes:
      - /mnt/c/Users/Gal1leo/Dev/new/slurm-web/slurm-web-docker/racksdb:/var/lib/racksdb:Z
      - /mnt/c/Users/Gal1leo/Dev/new/slurm-web/slurm-web-docker/slurm.conf:/etc/slurm/slurm.conf:Z
      - /mnt/c/Users/Gal1leo/Dev/new/slurm-web/slurm-web-docker/agent.ini:/etc/slurm-web/agent.ini:Z
      - /mnt/c/Users/Gal1leo/Dev/new/slurm-web/slurm-web-docker/gateway.ini:/etc/slurm-web/gateway.ini:Z
    restart: unless-stopped