version: '3.8'

services:
  sweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sweb
    ports:
      - "5011:5011"
      - "5012:5012"
    volumes:
      - ./racksdb:/var/lib/racksdb:Z
      - ./slurm.conf:/etc/slurm/slurm.conf:Z
      - ./agent.ini:/etc/slurm-web/agent.ini:Z
      - ./gateway.ini:/etc/slurm-web/gateway.ini:Z
      - ./munge.key:/etc/munge/munge.key:Z
    tty: true
    stdin_open: true
    restart: unless-stopped